/*

 BACKGOUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : D:\Github\Gameboy-Homebrew\Practice Code\Test 11\tiles\tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BackgroundTestWidth 20
#define BackgroundTestHeight 18
#define BackgroundTestBank 0

extern unsigned char BackgroundTest[];

/* End of BACKGOUND.H */
