/*

 WATERT.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char waterTile[] =
{
  0x00,0xB1,0x00,0x52,0x00,0x2A,0x00,0x59,
  0x00,0xCD,0x00,0x8C,0x00,0x9A,0x00,0xC1
};

/* End of WATERT.C */
